version: "3.8"

services:
  php:
    build:
        context: .
        target: php
        args:
            - APP_ENV=${APP_ENV}
    restart: always
    environment:
        - APP_ENV=${APP_ENV}
        - CONTAINER_ROLE=app
    working_dir: /var/www
    volumes:
        - ./:/var/www
    ports:
        - "8080:8080"
    depends_on:
        - mysql

  mysql:
    image: mysql:8.0
    restart: always
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    volumes:
      - db-data:/var/lib/mysql


volumes:
  db-data: ~
