version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - app-network

  php:
    build:
        context: .
        target: php
        args:
            - APP_ENV=${APP_ENV}
    restart: always
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - APP_ENV=${APP_ENV}
    working_dir: /var/www
    volumes:
        - ./:/var/www
    ports:
        - "8080:8080"
    depends_on:
        - mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db-data: ~
